apiVersion: v1
kind: Service
metadata:
  name: manshade
  namespace: manshade
  labels:
    app: manshade
spec:
  type: NodePort
  selector:
    app: manshade
  ports:
    - port: 31000
      targetPort: 3000
      nodePort: 31000
      name: http
